version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=coffeeDelivery
      - POSTGRES_DB=coffee
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
